@startuml

class Transaction {
    + value
}
class Creditor {
    + type
}
class Debtor {
    + type
}
class TransCostsPlan {
    + tax
    + rate
}
class TransCosts {
    + rate
    + tax
    + rate-valule
    + tax-value
}
class TransCostsSummary {
    + total
    + transactions
}
class TransCostsService {
    + calculate-transactions-costs()
}
enum UserType {
SPECIAL
REGULAR
}

Transaction --> "1" Creditor : has one
Transaction --> "1" Debtor : has one

Creditor --> "1" UserType
Debtor --> "1" UserType
TransCostsService ..> "1..*" Transaction : "calculates \ncosts"
TransCostsService .left.> TransCostsPlan : apply
Transaction --> "0..1" TransCosts : has
TransCostsService .right.> TransCostsSummary : returns
@enduml