@startuml

class Transaction {
    + value
}
class Creditor
class Debtor
class TransCostsPlan {
    + tax
    + rate
}
class TransCosts {
    + rate
    + tax
    + rate-valule
    + tax-value
}
class TransCostsSummary {
    + total
    + transactions
}
class TransCostsService {
    + calculate-transactions-costs()
}
enum UserType {
SPECIAL
REGULAR
}

Transaction --> "1" Creditor : has one
Transaction --> "1" Debtor : has one

Creditor --> "1" UserType
Debtor --> "1" UserType
TransCostsService ..> "*" Transaction : " calculates \ncosts of"
TransCostsService .left.> TransCostsPlan : load
Transaction --> "1" TransCosts : has
TransCostsService ..> TransCostsSummary : returns
@enduml